---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: openfortigui-deb11
    image: "geerlingguy/docker-debian11-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: openfortigui-deb12
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: openfortigui-ub22
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: openfortigui-ub24
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
